server:
  port: 8080

spring:
  application:
    name: mybatis-boost-integration-test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db.sql
      data-locations: classpath:data.sql
      continue-on-error: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      young1lin:
        mybatis:
          boost:
            integration:
              test: DEBUG
